name: 'Bump Versions'
description: 'A GitHub Action to easily bump version files'
author: 'Tommaso De Rossi'
branding:
  icon: 'chevrons-up'
  color: 'red'
inputs: 
  version_file:
    description: 'Version file to bump path'
    default: 'VERSION'
outputs:
  version:
    description: New version
  prefix:
    description: Prefix if set
runs:
  using: 'docker'
  image: 'Dockerfile'


  